import { readFile, writeFile } from "node:fs/promises"
import { resolve } from "node:path"
import { mergeBatch } from "./merge-batch"

const root = resolve(import.meta.dirname, "../..")
const path = resolve(root, "data/intelligence-snapshot.json")
const snapshot = JSON.parse(await readFile(path, "utf8"))
const batch = JSON.parse(await readFile(resolve(root, ".data/mac-batch/result.json"), "utf8"))
const result = mergeBatch(snapshot, batch)
const added = result.articles.length - snapshot.articles.length
if (added) {
  const payload = JSON.stringify(result)
  await writeFile(path, `${payload}\n`)
  await writeFile(resolve(root, "shared/intelligence-snapshot.ts"), "import type { IntelligenceArticle, IntelligenceSourceState } from \"./intelligence\"\n\n"
  + "export interface IntelligenceSnapshotSeen { key: string; at: number }\n"
  + "export interface IntelligenceSnapshot { generatedAt: number; articles: IntelligenceArticle[]; states: IntelligenceSourceState[]; seen: Record<string, IntelligenceSnapshotSeen[]> }\n\n"
  + "/** Generated by intelligence sync or tools/ai-bridge/apply-batch.ts. Do not edit manually. */\n"
  + `export const intelligenceSnapshot: IntelligenceSnapshot = ${payload}\n`)
}
console.log(JSON.stringify({ added, total: result.articles.length, note: "Local snapshot updated; publish through the existing repository deployment" }))
