import type { IntelligenceArticle, IntelligenceSourceState } from "./intelligence"

export interface IntelligenceSnapshotSeen {
  key: string
  at: number
}

export interface IntelligenceSnapshot {
  generatedAt: number
  articles: IntelligenceArticle[]
  states: IntelligenceSourceState[]
  seen: Record<string, IntelligenceSnapshotSeen[]>
}

/**
 * Generated by .github/workflows/intelligence-sync.yml.
 * Keep this checked in so Cloudflare Pages can serve durable intelligence data
 * without requiring a D1 database binding.
 */
export const intelligenceSnapshot: IntelligenceSnapshot = {
  generatedAt: 0,
  articles: [],
  states: [],
  seen: {},
}
