import type { SourceID } from "./types"

/**
 * 主题配置。
 * 主题不是新的抓取源，而是从现有热榜源中筛选并聚合相关内容。
 * 后续新增主题时，优先在这里增加配置，而不是复制一套抓取逻辑。
 */
export const healthTopic = {
  id: "health",
  name: "健康管理",
  description: "聚合全网热榜中与运动、体重管理、营养、睡眠和代谢健康相关的内容",
  /** 每个原始来源最多取多少条，普通 NewsNow 页面仍保持原来的 30 条。 */
  sourceLimit: 100,
  /** 送入 AI 做语义判断的跨源候选上限，避免一次请求过大。 */
  aiCandidateLimit: 180,
  /** AI 认为达到此相关度后进入健康管理主题。 */
  aiThreshold: 55,
  /** 主题页最终最多展示多少条。 */
  displayLimit: 80,
  sources: [
    "baidu",
    "weibo",
    "zhihu",
    "toutiao",
    "thepaper",
    "bilibili",
    "hupu",
    "smzdm",
  ] as const satisfies readonly SourceID[],
  keywords: [
    "健康管理",
    "健康",
    "运动",
    "健身",
    "锻炼",
    "减肥",
    "减脂",
    "减重",
    "肥胖",
    "体重",
    "体脂",
    "BMI",
    "跑步",
    "马拉松",
    "步数",
    "步行",
    "走路",
    "久坐",
    "力量训练",
    "有氧",
    "无氧",
    "肌肉",
    "增肌",
    "营养",
    "膳食",
    "饮食",
    "蛋白质",
    "热量",
    "卡路里",
    "睡眠",
    "失眠",
    "熬夜",
    "血糖",
    "血压",
    "血脂",
    "心率",
    "心肺",
    "心血管",
    "胆固醇",
    "糖尿病",
    "高血压",
    "脂肪肝",
    "代谢",
    "控糖",
    "体检",
    "疫苗",
    "GLP-1",
    "司美格鲁肽",
    "替尔泊肽",
  ],
} as const
